// <auto-generated />
using System;
using CovidGtAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CovidGtAPI.Migrations
{
    [DbContext(typeof(CovidGtDbContext))]
    [Migration("20201001172428_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("CovidGtAPI.Entities.CasoCovid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .IsFixedLength(true)
                        .HasMaxLength(1);

                    b.HasKey("Id");

                    b.ToTable("CasosCovid");
                });

            modelBuilder.Entity("CovidGtAPI.Entities.CasoCovid", b =>
                {
                    b.OwnsOne("CovidGtAPI.Entities.Localizacion", "Localizacion", b1 =>
                        {
                            b1.Property<long>("CasoCovidId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Departamento")
                                .HasColumnType("TEXT")
                                .HasMaxLength(32);

                            b1.Property<string>("Municipio")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasMaxLength(128);

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasMaxLength(128);

                            b1.HasKey("CasoCovidId");

                            b1.HasIndex("Departamento");

                            b1.HasIndex("Municipio");

                            b1.HasIndex("Pais");

                            b1.ToTable("CasosCovid");

                            b1.WithOwner()
                                .HasForeignKey("CasoCovidId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
